sample_data = [
    ["alpha bank romania s.a.",1],                                           
    ["banca comerciala carpatica",3],                                        
    ["banca comerciala feroviara s.a.",26],                                  
    ["banca comerciala intesa sanpaolo romania s.a.",22],                    
    ["banca comerciala romana s.a.",5],                                      
    ["banca millennium s.a.",24],                                            
    ["banca romaneasca s.a. membra a grupului national bank of greece",9],   
    ["banca transilvania s.a.",10],                                          
    ["bancpost s.a.",2],                                                     
    ["bank leumi romania s.a.",23],                                          
    ["bank of cyprus public company limited nicosia sucursala romania",25],  
    ["brd - groupe societe generale s.a.",8],                                
    ["cec bank s.a.",11],                                                    
    ["credit agricole bank romania s.a.",12],                                
    ["credit europe bank (romania) s.a.",13],                                
    ["garanti bank s.a.",14],                                                
    ["idea bank",20],                                                        
    ["ing bank n.v., amsterdam - sucursala bucuresti",15],                   
    ["libra internet bank s.a.",16],                                         
    ["nextebank s.a.",21],                                                   
    ["otp bank romania",4],                                                  
    ["piraeus bank romania s.a.",17],                                        
    ["procredit bank s.a.",18],                                              
    ["raiffeisen bank s.a.",19],                                             
    ["unicredit tiriac bank s.a.",6],                                        
    ["veneto banca romania",7]
]